services:
  # Loki in Monolithic mode (all-in-one)
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: "-config.file=/etc/loki/local-config.yaml"
    networks:
      - backend

  # Alloy as your "Everything Collector"
  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    ports:
      - "12345:12345"
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP (Spring Boot 4 sends here)
    networks:
      - backend

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - tempo-data:/var/tempo
      - type: bind
        source: ./observability/tempo/tempo.yaml
        target: /etc/tempo.yaml
        read_only: true
    ports:
      - "3200:3200" # For Grafana to Query
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        /run.sh
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./observability/grafana/datasource.yaml
        target: /etc/grafana/provisioning/datasources/datasource.yaml
        read_only: true
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.enable-remote-write-receiver' # REQUIRED for Alloy to push data
      - '--enable-feature=otlp-write-receiver' # Optional: future-proofing for OTLP
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    networks:
      - backend

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appservice
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - backend

  kafka:
    image: apache/kafka:4.1.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9091
      KAFKA_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9090,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - backend

  conduktor:
    image: conduktor/conduktor-console:latest
    container_name: conduktor-console
    ports:
      - "8888:8080" # Access via localhost:8888
    depends_on:
      conduktor-db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      # DATABASE CONFIG (This fixes your error)
      - CDK_DATABASE_URL=postgresql://conduktor:password@conduktor-db:5432/conduktor

      # INITIAL ADMIN USER
      - CDK_ADMIN_EMAIL=admin@conduktor.io
      - CDK_ADMIN_PASSWORD=Conduktor!123
      - CDK_CLUSTERS_0_ID=local-kafka-id
      # USE THESE SPECIFIC KEYS:
      - CDK_CLUSTERS_0_NAME=local-cluster
      - CDK_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9090
    networks:
      - backend

  conduktor-db:
    image: postgres:14-alpine
    container_name: conduktor-db
    environment:
      POSTGRES_DB: conduktor
      POSTGRES_USER: conduktor
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U conduktor" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend


volumes:
  tempo-data:
  kafka-data:

networks:
  backend:
    driver: "bridge"