services:
  app-service:
    build:
      context: ..
      dockerfile: app-service/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/appservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      OTEL_INSTRUMENTATION_JDBC_DATASOURCE_PEER_SERVICE_MAPPING: "appservice=mysql-appservice"
      #- OTEL_SERVICE_NAME=app-service
      #- OTEL_INSTRUMENTATION_COMMON_PEER_SERVICE_MAPPING=jsonplaceholder.typicode.com=JSONPlaceholder
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend: