server:
  port: 8080
spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      observation-enabled: true
  application:
    name: app-service

  datasource:
    url: jdbc:mysql://mysql:3306/appservice
    username: root
    password: root
    hikari:
      # Connection Pool Settings
      pool-name: appservice                    # Name shown in metrics/logs
      minimum-idle: 5                          # Minimum number of idle connections
      maximum-pool-size: 20                    # Maximum pool size
      max-lifetime: 1800000                    # Max lifetime of connection (30 min in ms)
      connection-timeout: 30000                # Timeout to get connection (30 sec)
      idle-timeout: 600000                     # Max idle time (10 min)


  sql:
    init:
      mode: always

logging:
  structured:
    format:
      console: "logstash"

otel:
  instrumentation:
    jdbc:
      enabled: true

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.client.requests: true
  opentelemetry:
    # This is the primary block for Spring Boot 4.0.1
    logging:
      export:
        otlp:
          endpoint: http://alloy:4318/v1/logs
    tracing:
      export:
        otlp:
          endpoint: http://alloy:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://alloy:4318/v1/metrics
        step: 10s
  tracing:
    sampling:
      probability: 1.0
  observations:
    http:
      client:
        requests:
          enabled: true
    annotations:
      enabled: true
