server:
  port: 8080
spring:
  application:
    name: app-service

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:appservice;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE;MODE=MySQL;NON_KEYWORDS=USER,USERS
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: always

logging:
  structured:
    format:
      console: "logstash"

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.client.requests: true
  opentelemetry:
    # This is the primary block for Spring Boot 4.0.1
    logging:
      export:
        otlp:
          endpoint: http://alloy:4318/v1/logs
    tracing:
      export:
        otlp:
          endpoint: http://alloy:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://alloy:4318/v1/metrics
        step: 10s
  tracing:
    sampling:
      probability: 1.0
  observations:
    http:
      client:
        requests:
          enabled: true
    annotations:
      enabled: true


springwolf:
  docket:
    base-package: com.example
    info:
      title: Product Service API
      version: 1.0.0
      description: AsyncAPI documentation for Product Events
    servers:
      kafka:
        host: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        protocol: kafka
        description: Kafka broker for product events
  scanner:
    kafka:
      listener:
        enabled: true
      producer:
        enabled: true