server:
  port: 8080
spring:
  application:
    name: app-service

logging:
  structured:
    format:
      console: "logstash"

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.client.requests: true
  opentelemetry:
    # This is the primary block for Spring Boot 4.0.1
    logging:
      export:
        otlp:
          endpoint: http://alloy:4318/v1/logs
    tracing:
      export:
        otlp:
          endpoint: http://alloy:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://alloy:4318/v1/metrics
        step: 10s
  tracing:
    sampling:
      probability: 1.0
  observations:
    http:
      client:
        requests:
          enabled: true
    annotations:
      enabled: true

