server:
  port: 8081
spring:
  application:
    name: kafka-consumer

  kafka:
    template:
      observation-enabled: true
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      listener:
        # This is the "Magic Fix": It retries the connection
        # if the broker/topic isn't ready at startup.
        missing-topics-fatal: false
        # If a rebalance happens, don't stop the whole container
        change-consumer-group-metadata: true
      auto-offset-reset: earliest
      properties:
        "schema.registry.url": "http://schema-registry:8081"
        "specific.avro.reader": "true"

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: ${spring.application.name}


otel:
  instrumentation:
    jdbc:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.client.requests: true
  opentelemetry:
    # This is the primary block for Spring Boot 4.0.1
    logging:
      export:
        otlp:
          endpoint: http://alloy:4318/v1/logs
    tracing:
      export:
        otlp:
          endpoint: http://alloy:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://alloy:4318/v1/metrics
        step: 10s
  tracing:
    sampling:
      probability: 1.0
  observations:
    http:
      client:
        requests:
          enabled: true
    annotations:
      enabled: true